---
ssh:
  banner: "Welcome back to Nest!"
  hostkeys:
    - /var/secrets/ssh_host_rsa_key
    - /var/secrets/ssh_host_ed25519_key
log:
  level: debug
auth:
  url: "http://localhost:3001"
  password: false
  pubkey: true
configserver:
  url: "http://localhost:3001/config"
backend: docker
docker:
  connection:
    host: unix:///var/run/docker.sock
